import { Sparkles, Copy, Check } from "lucide-react";
import { useState } from "react";

export default function AnswerPanel({ answer }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(answer);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="md:col-span-2">
      <div className="relative group">
        <div className="absolute -inset-1 bg-white/10 rounded-2xl blur opacity-0 group-hover:opacity-100 transition duration-300"></div>

        <div className="relative bg-zinc-900 border border-zinc-700 rounded-2xl shadow-2xl shadow-black/50 overflow-hidden">

          <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-700 bg-zinc-800/60">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-zinc-700 rounded-lg">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <h2 className="text-xl font-bold text-white">Analysis</h2>
            </div>

            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 hover:border-zinc-600 rounded-lg text-sm text-zinc-400 hover:text-white transition-all duration-200"
            >
              {copied ? (
                <><Check className="w-4 h-4" /> Copied!</>
              ) : (
                <><Copy  className="w-4 h-4" /> Copy</>
              )}
            </button>
          </div>

          <div className="p-6">
            <p className="text-zinc-200 leading-relaxed text-lg whitespace-pre-wrap">
              {answer}
            </p>
          </div>

          <div className="px-6 py-3 bg-zinc-800/50 border-t border-zinc-700">
            <div className="flex items-center gap-2 text-xs text-zinc-500">
              <div className="w-2 h-2 bg-white rounded-full animate-pulse"></div>
              Generated by AI • Always verify important financial decisions
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}